// Floor plan catalog data sourced from https://www.uhhomes.com/floor-plans/
const floorPlanCatalog = {
  vista: {
    name: "Vista",
    community: "Park Place",
    location: "Prosper, TX",
    description:
      "Experience a home design where architectural presence meets everyday comfort. This plan features soaring ceilings, an open foyer, and seamless indoor-outdoor flow through generous covered patios—ideal for entertaining or quiet relaxation. With a private suite, guest room, study, prayer space, and expansive upstairs retreat, it adapts effortlessly to your lifestyle for years.",
    specs: {
      bedrooms: 5,
      bathrooms: 5,
      halfBaths: 2,
      sqft: "5,059+",
      stories: 2,
      garage: 3,
    },
    dimensions: {
      totalArea: "5,060 Sqft",
      firstFloor: "3,654 Sqft",
      secondFloor: "1,405 Sqft",
    },
    elevationImages: [
      "https://www.uhhomes.com/wp-content/uploads/2026/03/exterior-ai-1771975839839-3.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/04/chinna-el2-1.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/05/Chinna-1920-X-1080-1.webp",
    ],
    floorPlanImages: [
      "https://www.uhhomes.com/wp-content/uploads/2026/03/Vista-F1-1.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/03/Vista-F2-1.webp",
    ],
    pdfUrl: "https://www.uhhomes.com/wp-content/uploads/2026/07/Vista.pdf",
    features: {
      kitchen: ["Kitchen Island", "L-Shaped", "Walk-in Pantry"],
      bedroom: ["Over-Sized Primary Suite Downstairs", "Guest Suite"],
      exterior: ["Second Floor Open Terrace", "3-Car Garage"],
      additional: [
        "Grand Foyer",
        "Prayer Room",
        "Office Room",
        "Dining Area",
        "Media Room",
        "Butler's Pantry",
        "Game Room",
        "Second Living",
        "One Mud Room",
        "Elevator Provision",
      ],
    },
    websiteUrl: "https://www.uhhomes.com/floor-plan/vista/",
  },
  utopia: {
    name: "Utopia",
    community: "Park Place",
    location: "Prosper, TX",
    description:
      "Experience a home design where transitional elegance meets everyday comfort. The Utopia Plan centers on an open foyer and bright, connected living spaces—ideal for family time, entertaining, or working from home. With a prep kitchen, private suite, guest room, office, and covered patio, it adapts effortlessly as your lifestyle evolves for years.",
    specs: {
      bedrooms: 5,
      bathrooms: 5,
      halfBaths: 2,
      sqft: "4,580+",
      stories: 2,
      garage: 3,
    },
    dimensions: {
      totalArea: "4,580 Sqft",
      firstFloor: "3,286 Sqft",
      secondFloor: "1,294 Sqft",
    },
    elevationImages: [
      "https://www.uhhomes.com/wp-content/uploads/2026/05/Utopia-Elev.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/05/Utopia-2.2-1.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/05/Utopia-3.2-1.webp",
    ],
    floorPlanImages: [
      "https://www.uhhomes.com/wp-content/uploads/2026/03/Scott-Plan-Template-F1.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/03/Scott-Plan-Template-F2.webp",
    ],
    pdfUrl: "https://www.uhhomes.com/wp-content/uploads/2026/07/Utopia.pdf",
    features: {
      kitchen: ["Kitchen Island", "L-Shaped"],
      bedroom: [
        "Over-Sized Primary Suite Downstairs",
        "Over-Sized Master Closet",
        "Guest Suite",
      ],
      exterior: ["3 Car Split Garage"],
      additional: [
        "Second Kitchen",
        "Second Study",
        "Prayer Room",
        "Office Room",
        "Dining Area",
        "Butler's Pantry",
        "Game Room",
        "Media Room",
        "One Mud Room",
        "Secondary Laundry Upstairs",
      ],
    },
    websiteUrl: "https://www.uhhomes.com/floor-plan/utopia/",
  },
  velora: {
    name: "Velora",
    community: "Park Place",
    location: "Prosper, TX",
    description:
      "Explore a home design that blends architectural finesse with everyday practicality. Our thoughtfully curated floorplans offer the perfect mix of open spaces and defined zones—ensuring flexibility for growing families, entertaining guests, or working remotely. Every inch is optimized for comfort, light, and flow, making each layout as livable as it is beautiful.",
    specs: {
      bedrooms: 5,
      bathrooms: 5,
      halfBaths: 2,
      sqft: "5,054+",
      stories: 2,
      garage: 3,
    },
    dimensions: {
      totalArea: "5,054 Sqft",
      firstFloor: "3,685 Sqft",
      secondFloor: "1,369 Sqft",
    },
    elevationImages: [
      "https://www.uhhomes.com/wp-content/uploads/2026/03/Front-Elevation-1-2.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/05/PP-1920-X-1080-1.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/05/PP-3840-X-2175-3.webp",
    ],
    floorPlanImages: [
      "https://www.uhhomes.com/wp-content/uploads/2026/03/Velora-F1-1-1.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/03/Velora-F2-1-1.webp",
    ],
    pdfUrl: "https://www.uhhomes.com/wp-content/uploads/2026/07/Velora.pdf",
    features: {
      kitchen: ["Kitchen Island", "L-Shaped", "Walk-In Pantry"],
      bedroom: [
        "Over-Sized Primary Suite Downstairs",
        "His & Her Closet",
        "Guest Suite",
      ],
      exterior: ["Second Floor Open Terrace", "3 Car Split Garage"],
      additional: [
        "Grand Staircase",
        "Prep Kitchen",
        "Prayer Room",
        "Office Room",
        "Dining Area",
        "Butler's Pantry",
        "Game Room",
        "Media Room",
        "Two Mud Rooms",
        "Elevator Provision",
      ],
    },
    websiteUrl: "https://www.uhhomes.com/floor-plan/velora/",
  },
  nexa: {
    name: "Nexa",
    community: "Park Place",
    location: "Prosper, TX",
    description:
      "The Nexa Plan offers a timeless design crafted for both comfort and function. Spacious single-level living, wide-open gathering spaces, and thoughtfully placed private zones create the ideal blend for families and entertainers alike. Every detail is designed for ease and flexibility—making it as practical as it is inviting, both now and for years ahead.",
    specs: {
      bedrooms: 4,
      bathrooms: 4,
      halfBaths: 1,
      sqft: "4,396+",
      stories: 1,
      garage: 3,
    },
    dimensions: {
      totalArea: "4,400 Sqft",
      firstFloor: "4,400 Sqft",
      secondFloor: null,
    },
    elevationImages: [
      "https://www.uhhomes.com/wp-content/uploads/2026/04/Ranch-Elevation-2-1.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/04/Ranch-Elevation-3.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/04/Ranch-Elevation-5.webp",
    ],
    floorPlanImages: [
      "https://www.uhhomes.com/wp-content/uploads/2026/03/Ranch-Template.webp",
    ],
    pdfUrl: "https://www.uhhomes.com/wp-content/uploads/2026/07/Nexa.pdf",
    features: {
      kitchen: ["Kitchen Island", "L-Shaped", "Walk-in Pantry"],
      bedroom: ["Master Suite", "Guest Suite"],
      exterior: [
        "Covered Front Porch",
        "Outdoor Kitchen",
        "Outdoor Living Space",
        "3 Car Split Garage",
      ],
      additional: [
        "Covered Patio",
        "Prayer Room",
        "Study Room",
        "Butler's Pantry",
        "Dining Area",
        "Game Room",
        "Mud Room",
      ],
    },
    websiteUrl: "https://www.uhhomes.com/floor-plan/nexa/",
  },
  zyra: {
    name: "Zyra",
    community: "Park Place",
    location: "Prosper, TX",
    description:
      "Experience a home design where modern elegance meets everyday comfort. The Zyra Plan features open-concept living areas balanced with private retreats—perfect for family time, entertaining, or working from home. With natural light, smart layouts, and seamless flow, the Zyra adapts effortlessly to your lifestyle today and as it evolves in the future.",
    specs: {
      bedrooms: 5,
      bathrooms: 5,
      halfBaths: 2,
      sqft: "4,263+",
      stories: 2,
      garage: 3,
    },
    dimensions: {
      totalArea: "4,263 Sqft",
      firstFloor: "3,122 Sqft",
      secondFloor: "1,142 Sqft",
    },
    elevationImages: [
      "https://www.uhhomes.com/wp-content/uploads/2026/04/Zyra-Elevation-2-2.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/04/Zyra-Elevation-3.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/05/Zyra-1-1.webp",
    ],
    floorPlanImages: [
      "https://www.uhhomes.com/wp-content/uploads/2026/03/Zyra-Template-F1-1.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/03/Zyra-Template-F2.webp",
    ],
    pdfUrl: "https://www.uhhomes.com/wp-content/uploads/2026/07/Zyra.pdf",
    features: {
      kitchen: ["Kitchen Island", "L-Shaped", "Walk-in Pantry"],
      bedroom: ["Master Suite Downstairs", "Guest Suite"],
      exterior: [
        "Covered Front Porch",
        "Outdoor Kitchen",
        "Outdoor Living Space",
      ],
      additional: [
        "Outdoor Kitchen",
        "Prayer Room",
        "Study Room",
        "Dining Area",
        "Game Room",
        "Courtyard",
        "Covered Patio",
        "Media Room Downstairs",
        "Second Floor Living Room",
        "3 Car Garage",
      ],
    },
    websiteUrl: "https://www.uhhomes.com/floor-plan/zyra/",
  },
  nirvaan: {
    name: "Nirvaan",
    community: "Park Place",
    location: "Prosper, TX",
    description:
      "From the moment you enter, a dramatic open foyer and interior courtyard create a grand yet welcoming first impression. The heart of the home features a vaulted-ceiling living area with fireplace, seamlessly connected to a chef's kitchen, butler's pantry, wine cellar, and formal dining—ideal for both intimate gatherings and elevated entertaining.",
    specs: {
      bedrooms: 5,
      bathrooms: 5,
      halfBaths: 2,
      sqft: "4,395+",
      stories: 2,
      garage: 3,
    },
    dimensions: {
      totalArea: "4,395 Sqft",
      firstFloor: "3,455 Sqft",
      secondFloor: "940 Sqft",
    },
    elevationImages: [
      "https://www.uhhomes.com/wp-content/uploads/2026/04/Nirvaan-Elevation-2.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/03/Nirvaan-Elevation-5.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/04/exterior-ai-1771975982061-3.webp",
    ],
    floorPlanImages: [
      "https://www.uhhomes.com/wp-content/uploads/2026/03/Nirvaan-F1-1-1.webp",
      "https://www.uhhomes.com/wp-content/uploads/2026/03/Nirvaan-F2-1-1.webp",
    ],
    pdfUrl: "https://www.uhhomes.com/wp-content/uploads/2026/05/Nirvaan-2.pdf",
    features: {
      kitchen: ["Kitchen Island", "L-Shaped", "Prep Kitchen"],
      bedroom: [
        "Over-Sized Primary Suite Downstairs",
        "Guest Suite",
        "Master Closet",
        "Additional Bedroom Downstairs",
      ],
      exterior: ["Front Courtyard", "Tandem 3 Car Garage"],
      additional: [
        "Open Foyer",
        "Office Room",
        "Dining Area",
        "Two Game Rooms",
        "Media Room",
        "One Mud Room",
      ],
    },
    websiteUrl: "https://www.uhhomes.com/floor-plan/nirvaan/",
  },
};

export default floorPlanCatalog;
